version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: nest_postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASENAME}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

  app:
    build: .
    container_name: nest_app
    depends_on:
      - postgres
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASENAME=${DB_DATABASENAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_URL=${DB_URL}
      - DB_PORT=${DB_PORT}
    ports:
      - '3001:3001'
    # environment:
    #   DATABASE_URL: postgres://postgres:postgres@postgres:5432/task_db
    # volumes:
    #   - .:/app
    command: yarn start:prod
volumes:
  postgres_data:
